// ocbridge OpenCode command plugin (MVP+UX)
// Provides commands that interact with local ocbridge daemon HTTP API.
// This is a lightweight shim; the daemon owns NATS connection + store.

import http from 'node:http'
import { URL } from 'node:url'
import os from 'node:os'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

const DEFAULT_BASE = process.env.OCBRIDGE_API || 'http://127.0.0.1:7341'
const CONFIG_DIR = path.join(os.homedir(), '.config', 'ocbridge')
const CONFIG_FILE = path.join(CONFIG_DIR, 'env')

const ENV_KEYS = [
  'NATS_URL',
  'OC_NODE_ID',
  'NODE_ID',
  'CAPABILITY',
  'CHAT_TO_PREFIX',
  'CHAT_FROM_PREFIX',
  'DISPATCH_SUBJECTS',
  'RESULT_SUBJECTS',
  'DISPATCH_SUBJECT',
  'RESULT_SUBJECT',
  'EVENTS_PREFIX',
  'HEARTBEAT_SUBJECT',
  'RUN_TIMEOUT',
  'OPENCODE_SERVE_HOST',
  'OPENCODE_SERVE_PORT',
  'OCBRIDGE_DB',
]

function ensureSessionId() {
  // Persist per-user session id so multiple TUIs can be distinguished.
  const dir = path.join(os.homedir(), '.local', 'share', 'ocbridge')
  const file = path.join(dir, 'session_id')
  try {
    fs.mkdirSync(dir, { recursive: true })
    if (fs.existsSync(file)) {
      const v = fs.readFileSync(file, 'utf8').trim()
      if (v) return v
    }
    const sid = crypto.randomUUID()
    fs.writeFileSync(file, sid + '\n', 'utf8')
    return sid
  } catch {
    // fallback: still return a stable id for this process
    return crypto.randomUUID()
  }
}

const SESSION_ID = process.env.OCBRIDGE_SESSION_ID || ensureSessionId()

function requestJson(pathname, { method = 'GET', body = null } = {}) {
  const url = new URL(pathname, DEFAULT_BASE)
  return new Promise((resolve, reject) => {
    const payload = body ? Buffer.from(JSON.stringify(body)) : null
    const req = http.request(
      {
        method,
        hostname: url.hostname,
        port: url.port,
        path: url.pathname + url.search,
        headers: {
          'content-type': 'application/json',
          'x-session-id': SESSION_ID,
          ...(payload ? { 'content-length': payload.length } : {}),
        },
      },
      (res) => {
        const chunks = []
        res.on('data', (d) => chunks.push(d))
        res.on('end', () => {
          const text = Buffer.concat(chunks).toString('utf8')
          if (res.statusCode && res.statusCode >= 400) {
            reject(new Error(`HTTP ${res.statusCode}: ${text}`))
            return
          }
          try {
            resolve(text ? JSON.parse(text) : {})
          } catch {
            reject(new Error(`Invalid JSON: ${text.slice(0, 200)}`))
          }
        })
      }
    )
    req.on('error', reject)
    if (payload) req.write(payload)
    req.end()
  })
}

function defaultEnvConfig() {
  const node = process.env.OC_NODE_ID || process.env.NODE_ID || os.hostname()
  return {
    NATS_URL: process.env.NATS_URL || 'nats://100.95.183.80:4222',
    OC_NODE_ID: node,
    NODE_ID: node,
    CAPABILITY: process.env.CAPABILITY || 'coding',
    CHAT_TO_PREFIX: process.env.CHAT_TO_PREFIX || 'oc.chat.to.',
    CHAT_FROM_PREFIX: process.env.CHAT_FROM_PREFIX || 'oc.chat.from.',
    DISPATCH_SUBJECTS: process.env.DISPATCH_SUBJECTS || 'openclaw.dispatch.v1,op.task.home',
    RESULT_SUBJECTS: process.env.RESULT_SUBJECTS || 'openclaw.result.v1,op.result.controller',
    DISPATCH_SUBJECT: process.env.DISPATCH_SUBJECT || '',
    RESULT_SUBJECT: process.env.RESULT_SUBJECT || '',
    EVENTS_PREFIX: process.env.EVENTS_PREFIX || 'oc.task.event',
    HEARTBEAT_SUBJECT: process.env.HEARTBEAT_SUBJECT || 'oc.worker.heartbeat',
    RUN_TIMEOUT: process.env.RUN_TIMEOUT || '900',
    OPENCODE_SERVE_HOST: process.env.OPENCODE_SERVE_HOST || '127.0.0.1',
    OPENCODE_SERVE_PORT: process.env.OPENCODE_SERVE_PORT || '4096',
    OCBRIDGE_DB: process.env.OCBRIDGE_DB || '$HOME/.local/share/ocbridge/bridge.db',
  }
}

function parseEnvFile(text) {
  const out = {}
  const lines = String(text || '').split(/\r?\n/)
  for (const line of lines) {
    const s = line.trim()
    if (!s || s.startsWith('#')) continue
    const m = s.match(/^export\s+([A-Z0-9_]+)=(.*)$/)
    if (!m) continue
    const key = m[1]
    let val = m[2].trim()
    if ((val.startsWith("'") && val.endsWith("'")) || (val.startsWith('"') && val.endsWith('"'))) {
      val = val.slice(1, -1)
    }
    out[key] = val
  }
  return out
}

function shellQuote(v) {
  const s = String(v ?? '')
  return `'${s.replaceAll("'", `'"'"'`)}'`
}

function formatEnvFile(cfg) {
  const lines = [
    '# ocbridge env generated by /oc-setup or /oc-reconfigure',
    '# source ~/.config/ocbridge/env',
    '',
  ]
  for (const key of ENV_KEYS) {
    lines.push(`export ${key}=${shellQuote(cfg[key] ?? '')}`)
  }
  lines.push('')
  return lines.join('\n')
}

function loadEnvConfig() {
  const base = defaultEnvConfig()
  try {
    if (fs.existsSync(CONFIG_FILE)) {
      const parsed = parseEnvFile(fs.readFileSync(CONFIG_FILE, 'utf8'))
      return { ...base, ...parsed }
    }
  } catch {
    return base
  }
  return base
}

function saveEnvConfig(cfg) {
  fs.mkdirSync(CONFIG_DIR, { recursive: true })
  fs.writeFileSync(CONFIG_FILE, formatEnvFile(cfg), 'utf8')
}

function maskValue(key, value) {
  const v = String(value ?? '')
  const upper = String(key || '').toUpperCase()
  const sensitive = ['TOKEN', 'SECRET', 'PASSWORD', 'KEY', 'CREDS']
  if (sensitive.some((k) => upper.includes(k))) {
    if (!v) return ''
    if (v.length <= 6) return '***'
    return `${v.slice(0, 3)}***${v.slice(-2)}`
  }
  if (upper === 'NATS_URL') {
    return v.replace(/:\/\/([^:@/]+):([^@/]+)@/g, '://$1:***@')
  }
  return v
}

function renderConfig(cfg, { masked = true } = {}) {
  const out = {}
  for (const key of ENV_KEYS) {
    const raw = cfg[key] ?? ''
    out[key] = masked ? maskValue(key, raw) : raw
  }
  return out
}

function parseKvPairs(args) {
  const patch = {}
  for (const token of args || []) {
    if (!token.includes('=')) continue
    const idx = token.indexOf('=')
    const key = token.slice(0, idx).trim().toUpperCase()
    const value = token.slice(idx + 1)
    if (!key) continue
    patch[key] = value
  }
  return patch
}

function formatEventLine(event) {
  const payload = event?.payload || {}
  const ts = Number(event?.ts || payload?.ts || Date.now() / 1000)
  const when = new Date(ts * 1000).toISOString()
  const taskId = payload.task_id || event.task_id || '-'
  const phase = payload.phase || payload.summary || payload.status || '-'
  const node = payload.node_id || payload.node || '-'
  const message = payload.message || payload.stderr_tail || payload.stdout_tail || ''
  const msg = String(message).replace(/\s+/g, ' ').slice(0, 120)
  return `[${when}] task=${taskId} phase=${phase} node=${node}${msg ? ` msg=${msg}` : ''}`
}

function parseEventArgs(args) {
  const out = {
    follow: false,
    limit: 50,
    sinceTs: 0,
    timeoutMs: 25000,
    seconds: 30,
  }
  for (const raw of args || []) {
    const a = String(raw || '').trim()
    if (!a) continue
    if (a === '--follow' || a === '-f') {
      out.follow = true
      continue
    }
    if (a.startsWith('--limit=')) {
      out.limit = Number(a.slice('--limit='.length)) || out.limit
      continue
    }
    if (a.startsWith('--since=')) {
      out.sinceTs = Number(a.slice('--since='.length)) || out.sinceTs
      continue
    }
    if (a.startsWith('--timeout-ms=')) {
      out.timeoutMs = Number(a.slice('--timeout-ms='.length)) || out.timeoutMs
      continue
    }
    if (a.startsWith('--seconds=')) {
      out.seconds = Number(a.slice('--seconds='.length)) || out.seconds
    }
  }
  return out
}

async function runEventsCommand(args, forceFollow = false) {
  const opt = parseEventArgs(args)
  if (forceFollow) opt.follow = true

  let sinceTs = opt.sinceTs
  if (!opt.follow) {
    const out = await requestJson(`/events?since_ts=${encodeURIComponent(sinceTs)}&limit=${encodeURIComponent(opt.limit)}&timeout_ms=1`)
    const events = out?.events || []
    const lines = events.map(formatEventLine)
    return lines.join('\n') || '(no events)'
  }

  const endAt = Date.now() + Math.max(1, opt.seconds) * 1000
  const lines = [
    `following /events for ${opt.seconds}s (timeout_ms=${opt.timeoutMs}, limit=${opt.limit}) ...`,
  ]
  while (Date.now() < endAt) {
    const out = await requestJson(
      `/events?since_ts=${encodeURIComponent(sinceTs)}&limit=${encodeURIComponent(opt.limit)}&timeout_ms=${encodeURIComponent(opt.timeoutMs)}`
    )
    const events = out?.events || []
    if (events.length > 0) {
      for (const ev of events) {
        lines.push(formatEventLine(ev))
      }
      const last = events[events.length - 1]
      const ts = Number(last?.ts || last?.payload?.ts || sinceTs)
      sinceTs = ts > 0 ? ts + 0.000001 : sinceTs
    }
  }
  if (lines.length === 1) lines.push('(no events in follow window)')
  return lines.join('\n')
}

export default {
  name: 'ocbridge',
  description: 'ocbridge commands (inbox/status/reply/mode/setup/events) via local daemon',
  commands: {
    'oc-status': async () => {
      const st = await requestJson('/status')
      return JSON.stringify(st, null, 2)
    },
    'oc-doctor': async () => {
      const out = await requestJson('/doctor')
      return JSON.stringify(out, null, 2)
    },
    'oc-logs': async ({ args }) => {
      const lines = Number(args?.[0] || 50)
      const out = await requestJson(`/logs?lines=${encodeURIComponent(lines)}`)
      return JSON.stringify(out, null, 2)
    },
    'oc-setup': async ({ args }) => {
      const force = (args || []).includes('--force')
      const exists = fs.existsSync(CONFIG_FILE)
      const cfg = loadEnvConfig()
      if (!exists || force) {
        saveEnvConfig(cfg)
      }
      return [
        exists && !force ? 'config exists (use /oc-setup --force to overwrite defaults)' : 'config skeleton created',
        `path: ${CONFIG_FILE}`,
        'sanitized preview:',
        JSON.stringify(renderConfig(cfg, { masked: true }), null, 2),
      ].join('\n')
    },
    'oc-reconfigure': async ({ args }) => {
      const showOnly = !args || args.length === 0 || args.includes('--show')
      const cfg = loadEnvConfig()
      if (showOnly) {
        return [
          `path: ${CONFIG_FILE}`,
          'current config (sanitized):',
          JSON.stringify(renderConfig(cfg, { masked: true }), null, 2),
          'usage: /oc-reconfigure KEY=value [KEY=value ...]',
        ].join('\n')
      }
      const patch = parseKvPairs(args)
      const keys = Object.keys(patch)
      if (keys.length === 0) {
        throw new Error('usage: /oc-reconfigure KEY=value [KEY=value ...]')
      }
      const merged = { ...cfg, ...patch }
      saveEnvConfig(merged)
      return [
        `updated: ${keys.join(', ')}`,
        `path: ${CONFIG_FILE}`,
        'updated config (sanitized):',
        JSON.stringify(renderConfig(merged, { masked: true }), null, 2),
      ].join('\n')
    },
    'oc-inbox': async ({ args }) => {
      const limit = Number(args?.[0] || 20)
      const rows = await requestJson(`/inbox?limit=${encodeURIComponent(limit)}`)
      return JSON.stringify(rows, null, 2)
    },
    'oc-pending': async ({ args }) => {
      const limit = Number(args?.[0] || 20)
      const rows = await requestJson(`/pending?limit=${encodeURIComponent(limit)}`)
      return JSON.stringify(rows, null, 2)
    },
    'oc-events': async ({ args }) => {
      return await runEventsCommand(args || [], false)
    },
    'oc-follow': async ({ args }) => {
      return await runEventsCommand(args || [], true)
    },
    'oc-claim': async ({ args }) => {
      const taskId = args?.[0]
      if (!taskId) throw new Error('usage: /oc-claim <task_id>')
      const out = await requestJson('/claim', {
        method: 'POST',
        body: { task_id: taskId, session_id: SESSION_ID },
      })
      return JSON.stringify(out, null, 2)
    },
    'oc-run': async ({ args }) => {
      const taskId = args?.[0]
      if (!taskId) throw new Error('usage: /oc-run <task_id>')
      const out = await requestJson('/run', {
        method: 'POST',
        body: { task_id: taskId, session_id: SESSION_ID },
      })
      return JSON.stringify(out, null, 2)
    },
    'oc-reply': async ({ args }) => {
      const taskId = args?.[0]
      const text = args?.slice(1).join(' ')
      if (!taskId || !text) throw new Error('usage: /oc-reply <task_id> <text>')
      const out = await requestJson('/publish', {
        method: 'POST',
        body: { kind: 'chat', task_id: taskId, text, session_id: SESSION_ID },
      })
      return JSON.stringify(out, null, 2)
    },
    'oc-session': async () => {
      return JSON.stringify({ session_id: SESSION_ID }, null, 2)
    },
    'oc-whoami': async () => {
      const out = await requestJson('/whoami')
      return JSON.stringify(out, null, 2)
    },
    'oc-mode': async ({ args }) => {
      const mode = (args?.[0] || '').toLowerCase()
      if (!mode || (mode !== 'auto' && mode !== 'manual')) throw new Error('usage: /oc-mode auto|manual')
      const out = await requestJson('/mode', {
        method: 'POST',
        body: { mode },
      })
      return JSON.stringify(out, null, 2)
    },
  },
}
