#!/usr/bin/env bash
set -euo pipefail

# RouteA one-shot interactive installer for ocbridge + OpenCode plugin
# - clones repo (or uses current dir)
# - creates venv and installs deps
# - generates ocbridge env + optional systemd user service
# - explains plugin enablement

bold() { printf "\033[1m%s\033[0m\n" "$*"; }
info() { printf "[info] %s\n" "$*"; }
warn() { printf "[warn] %s\n" "$*" >&2; }
err() { printf "[err] %s\n" "$*" >&2; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || { err "missing command: $1"; exit 1; }
}

ask() {
  local prompt="$1"; local default="${2:-}"; local out
  if [ -n "$default" ]; then
    printf "%s" "${prompt} [${default}]: " >&2
    IFS= read -r out || out=""
    echo "${out:-$default}"
  else
    printf "%s" "${prompt}: " >&2
    IFS= read -r out || out=""
    echo "$out"
  fi
}

ask_yn() {
  local prompt="$1"; local default="${2:-y}"; local out
  printf "%s" "${prompt} (y/n) [${default}]: " >&2
  IFS= read -r out || out=""
  out="${out:-$default}"
  [[ "$out" =~ ^[Yy]$ ]]
}

sanitize_node_id() {
  echo "$1" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9_-' '-'
}

main() {
  bold "RouteA 一键安装（ocbridge + OpenCode TUI 插件）"

  need_cmd git
  need_cmd python3

  local repo_dir
  repo_dir="$(pwd)"

  if [ ! -f "$repo_dir/requirements.txt" ] || [ ! -d "$repo_dir/ocbridge" ]; then
    if ask_yn "当前目录看起来不是 opencode-openclaw-collab 仓库，是否自动 clone 到 ~/opencode-openclaw-collab？" y; then
      repo_dir="$HOME/opencode-openclaw-collab"
      if [ -d "$repo_dir/.git" ]; then
        info "已存在仓库：$repo_dir（将执行 git pull）"
        git -C "$repo_dir" pull --ff-only
      else
        git clone https://github.com/duoglas/opencode-openclaw-collab.git "$repo_dir"
      fi
    else
      err "请在仓库根目录运行该脚本。"
      exit 1
    fi
  fi

  info "使用仓库目录：$repo_dir"

  # venv
  local venv_dir="$repo_dir/.venv"
  if [ ! -x "$venv_dir/bin/python" ]; then
    info "创建 venv：$venv_dir"
    python3 -m venv "$venv_dir"
  fi
  "$venv_dir/bin/pip" install -q -r "$repo_dir/requirements.txt"

  # basic checks
  if command -v opencode >/dev/null 2>&1; then
    info "检测到 opencode：$(opencode --version 2>/dev/null || true)"
  else
    warn "未检测到 opencode 命令。ocbridge 运行任务需要 opencode。请先安装并确保 opencode --version 可用。"
  fi

  # collect config
  local nats_url node_id mode creds_path
  nats_url="$(ask "NATS_URL" "nats://100.95.183.80:4222")"
  node_id="$(ask "NODE_ID（仅允许 a-z0-9_-，不要包含点号）" "$(hostname -s 2>/dev/null || echo worker-01)")"
  node_id="$(sanitize_node_id "$node_id")"
  mode="$(ask "OCBRIDGE_MODE（auto/manual）" "manual")"
  creds_path="$(ask "NATS_CREDS 路径（可留空=无鉴权；建议填 opencode_worker.creds）" "$HOME/.config/ocbridge/opencode_worker.creds")"

  mkdir -p "$HOME/.config/ocbridge"

  # write env
  local env_file="$HOME/.config/ocbridge/env"
  cat > "$env_file" <<EOF
# RouteA ocbridge env (generated by install_routeA.sh)
NATS_URL='${nats_url}'
NATS_CREDS='${creds_path}'
NODE_ID='${node_id}'
CAPABILITY='coding'
OCBRIDGE_MODE='${mode}'

DISPATCH_SUBJECTS='openclaw.dispatch.v1,op.task.home'
RESULT_SUBJECTS='openclaw.result.v1,op.result.controller'

CHAT_TO_PREFIX='oc.chat.to.'
CHAT_FROM_PREFIX='oc.chat.from.'

OPENCODE_SERVE_HOST='127.0.0.1'
OPENCODE_SERVE_PORT='4096'

OCBRIDGE_DB="\$HOME/.local/share/ocbridge/bridge.db"
OCBRIDGE_API_HOST='127.0.0.1'
OCBRIDGE_API_PORT='7341'
EOF
  chmod 600 "$env_file"
  info "已生成：$env_file"

  # optional: systemd user service
  if command -v systemctl >/dev/null 2>&1 && ask_yn "是否安装为 systemd --user 服务（开机自启）？" y; then
    mkdir -p "$HOME/.config/systemd/user"
    local svc="$HOME/.config/systemd/user/ocbridge.service"
    cat > "$svc" <<EOF
[Unit]
Description=ocbridge RouteA daemon
After=network-online.target

[Service]
Type=simple
WorkingDirectory=${repo_dir}
EnvironmentFile=%h/.config/ocbridge/env
ExecStart=${repo_dir}/.venv/bin/python -m ocbridge.bridge_daemon
Restart=always
RestartSec=2

[Install]
WantedBy=default.target
EOF

    systemctl --user daemon-reload
    systemctl --user enable --now ocbridge.service
    info "已启动：systemctl --user status ocbridge.service"
  else
    bold "手动启动方式："
    echo "source ~/.config/ocbridge/env"
    echo "cd ${repo_dir}"
    echo "source .venv/bin/activate"
    echo "python -m ocbridge.bridge_daemon"
  fi

  bold "OpenCode 插件启用（需按你的 opencode 版本配置）"
  echo "插件目录：${repo_dir}/plugin/ocbridge"
  echo "如果你不确定如何加载插件，把 ~/.config/opencode/opencode.json 发我，我会按你的版本给出唯一可用配置。"

  bold "快速自检"
  echo "curl -s http://127.0.0.1:7341/status"
  echo "脚本（E2E）：${repo_dir}/scripts/oc_reply_e2e.sh"

  info "完成。"
}

main "$@"
